/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import Telas.CadastroClientes;
import Telas.Panel1;
import Telas.Panel2;
import fontes.CadastroCliente;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import menu.teste;

/**
 *
 * @author guilh
 */
public class Tl_principalpi extends javax.swing.JFrame {

    /**
     * Creates new form Tl_principalpi
     */
    public Tl_principalpi() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        execute();
    }

    private void execute() {
        ImageIcon iconUser = new ImageIcon(getClass().getResource("/menu/usuario.png"));
        ImageIcon iconCadastro = new ImageIcon(getClass().getResource("/menu/cadastro.png"));
        ImageIcon iconCompra = new ImageIcon(getClass().getResource("/menu/compra.png"));
        ImageIcon iconRelatorio = new ImageIcon(getClass().getResource("/menu/relatorio.png"));
        ImageIcon iconSubmenu = new ImageIcon(getClass().getResource("/menu/submenu.png"));

        teste menuUser1 = new teste(iconSubmenu, "Meu Perfil", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                painelCorpo.removeAll();
                painelCorpo.add(new Panel1());
                painelCorpo.repaint();
                painelCorpo.revalidate();
            }
        });
        teste menuUser2 = new teste(iconSubmenu, "Minhas Vendas", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                painelCorpo.removeAll();
                painelCorpo.add(new Panel2());
                painelCorpo.repaint();
                painelCorpo.revalidate();
            }
        });
        teste menuUser3 = new teste(iconSubmenu, "Sair",null);

        teste menuCadastro1 = new teste(iconSubmenu, "Cliente",new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                painelCorpo.removeAll();
                painelCorpo.add(new CadastroClientes());
                painelCorpo.repaint();
                painelCorpo.revalidate();
            }
        });
        teste menuCadastro2 = new teste(iconSubmenu, "Fornecedor",null);
        teste menuCadastro3 = new teste(iconSubmenu, "Colaborador",null);

        teste menuCompra1 = new teste(iconSubmenu, "Venda de Produto", null);
        teste menuCompra2 = new teste(iconSubmenu, "Compra de Produto",null);
        teste menuCompra3 = new teste(iconSubmenu, "Historico do Dia",null);

        teste menuRelatorio1 = new teste(iconSubmenu, "Analitíco",null);
        teste menuRelotorio2 = new teste(iconSubmenu, "Sintético",null);

        teste menuUser = new teste(iconUser, "USUÁRIO", null, menuUser1, menuUser2, menuUser3);
        teste menuCadastro = new teste(iconCadastro, "CADASTROS", null, menuCadastro1, menuCadastro2, menuCadastro3);
        teste menuCompra = new teste(iconCompra, "VENDA/COMPRA", null, menuCompra1, menuCompra2, menuCompra3);
        teste menuRelatorio = new teste(iconRelatorio, "RELATÓRIOS", null, menuRelatorio1, menuRelotorio2);

        addmenu(menuUser, menuCadastro, menuCompra, menuRelatorio);

    }

    private void addmenu(teste... menu) {
        for (int i = 0; i < menu.length; i++) {
            menus.add(menu[i]);

            ArrayList<teste> subMenu = menu[i].getSubMenu();
            for (teste m : subMenu) {
                addmenu(m);
            }
        }
        menus.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        painelCabeca = new javax.swing.JPanel();
        painelMenu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menus = new javax.swing.JPanel();
        painelCorpo = new javax.swing.JPanel();

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("cadastros");

        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelCabeca.setBackground(new java.awt.Color(87, 188, 144));
        painelCabeca.setPreferredSize(new java.awt.Dimension(795, 50));

        javax.swing.GroupLayout painelCabecaLayout = new javax.swing.GroupLayout(painelCabeca);
        painelCabeca.setLayout(painelCabecaLayout);
        painelCabecaLayout.setHorizontalGroup(
            painelCabecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        painelCabecaLayout.setVerticalGroup(
            painelCabecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(painelCabeca, java.awt.BorderLayout.PAGE_START);

        painelMenu.setBackground(new java.awt.Color(204, 204, 204));
        painelMenu.setPreferredSize(new java.awt.Dimension(250, 375));

        jScrollPane1.setBorder(null);

        menus.setBackground(new java.awt.Color(1, 82, 73));
        menus.setLayout(new javax.swing.BoxLayout(menus, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(menus);

        javax.swing.GroupLayout painelMenuLayout = new javax.swing.GroupLayout(painelMenu);
        painelMenu.setLayout(painelMenuLayout);
        painelMenuLayout.setHorizontalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        painelMenuLayout.setVerticalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );

        getContentPane().add(painelMenu, java.awt.BorderLayout.LINE_START);

        painelCorpo.setBackground(new java.awt.Color(204, 204, 204));
        painelCorpo.setLayout(new java.awt.BorderLayout());
        getContentPane().add(painelCorpo, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(811, 464));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tl_principalpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tl_principalpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tl_principalpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tl_principalpi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tl_principalpi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menus;
    private javax.swing.JPanel painelCabeca;
    private javax.swing.JPanel painelCorpo;
    private javax.swing.JPanel painelMenu;
    // End of variables declaration//GEN-END:variables
}
